# Netlify 主项目配置 - 用于部署 skillhub-nz
# 请将此文件重命名为 netlify.toml 并放置在 skillhub-nz 目录下

[build]
  # 基础目录设置为 skillhub-nz
  base = "skillhub-nz"
  # 构建命令
  command = "npm run build:netlify"
  # 发布目录设置为 Next.js 输出的 out 目录
  publish = "skillhub-nz/out"

[build.environment]
  NODE_VERSION = "18"
  # Firebase 环境变量
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBEXwf9SCerk1XUSeWBlduL7nU-VbMxWu8"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "kiwispark-80e5d.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "kiwispark-80e5d"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "kiwispark-80e5d.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "287274562407"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:287274562407:web:1fac7d76f212e3843035c2"

# 重定向规则
# 根路径重定向到中文版
[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302

# 处理静态资源
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# 处理 locale 路由
[[redirects]]
  from = "/zh/*"
  to = "/zh/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

# SPA 路由回退
[[redirects]]
  from = "/*"
  to = "/zh/index.html"
  status = 200
