# Netlify 配置（Next Runtime，启用 SSR / Middleware / API）

[build]
  base = "skillhub-nz"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # 客户端 Firebase（可迁移至 Netlify 环境变量管理）
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBEXwf9SCerk1XUSeWBlduL7nU-VbMxWu8"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "kiwispark-80e5d.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "kiwispark-80e5d"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "kiwispark-80e5d.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "287274562407"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:287274562407:web:1fac7d76f212e3843035c2"

# 注意：FIREBASE_PRIVATE_KEY 等管理端密钥请在 Netlify 控制台设置，勿提交到仓库

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  # 不需要手动为 /api/* 添加重写，Next 插件会自动处理 API / Middleware / 图片优化
