[build]
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Redirect root to default locale
[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302

# Handle locale routes
[[redirects]]
  from = "/zh/*"
  to = "/zh/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

# Handle static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Fallback for SPA routing - redirect to default locale
[[redirects]]
  from = "/*"
  to = "/zh/"
  status = 200
