// 这是一个演示用的数据种子文件
// 在实际应用中，这些数据应该通过管理界面或API来创建

import { Timestamp } from 'firebase/firestore';

export const demoCategories = [
  {
    id: 'cat-1',
    name: '马术',
    description: '学习马术基础技能、马匹护理和高级骑术技巧',
    color: 'brown',
    icon: '🐎',
    isActive: true,
    sortOrder: 1,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'cat-2',
    name: '高尔夫',
    description: '高尔夫球技训练、球场策略和比赛技巧',
    color: 'green',
    icon: '⛳',
    isActive: true,
    sortOrder: 2,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoUsers = [
  {
    id: 'user-1',
    email: 'mike@example.com',
    displayName: 'Mike Thompson',
    role: 'coach',
    bio: '拥有15年马术教学经验，新西兰马术协会认证教练，专精于障碍赛和盛装舞步',
    location: '奥克兰',
    isVerified: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'user-2',
    email: 'lisa@example.com',
    displayName: 'Lisa Chen',
    role: 'coach',
    bio: '职业高尔夫球手，PGA认证教练，曾获得多项新西兰高尔夫锦标赛冠军',
    location: '惠灵顿',
    isVerified: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoCoaches = [
  {
    id: 'coach-1',
    userId: 'user-1',
    specialties: ['障碍赛', '盛装舞步', '马匹护理', '基础骑术'],
    experience: 15,
    education: ['马术科学学士', '马匹管理硕士'],
    certifications: ['新西兰马术协会认证教练', 'FEI国际马术联合会认证'],
    hourlyRate: 150,
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: false,
    },
    rating: 4.9,
    totalReviews: 203,
    isActive: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'coach-2',
    userId: 'user-2',
    specialties: ['高尔夫挥杆', '短杆技巧', '推杆技术', '球场策略'],
    experience: 12,
    education: ['体育科学学士', '高尔夫管理硕士'],
    certifications: ['PGA职业高尔夫协会认证', '新西兰高尔夫协会认证教练'],
    hourlyRate: 180,
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: true,
    },
    rating: 4.8,
    totalReviews: 167,
    isActive: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoCourses = [
  {
    id: 'course-1',
    title: '马术基础入门',
    description: '从零开始学习马术基础技能，包括马匹护理、基本骑术姿势、安全知识等。适合完全没有马术经验的初学者。',
    coachId: 'coach-1',
    categoryId: 'cat-1',
    price: 450,
    duration: 600, // 10小时
    maxStudents: 8,
    currentStudents: 6,
    level: 'beginner',
    tags: ['马术基础', '马匹护理', '安全知识', '骑术姿势'],
    images: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.9,
    totalReviews: 78,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-2',
    title: '高尔夫挥杆技巧',
    description: '学习高尔夫球的基本挥杆技巧，包括站姿、握杆、挥杆动作等。通过专业指导和练习，快速提升你的高尔夫球技。',
    coachId: 'coach-2',
    categoryId: 'cat-2',
    price: 380,
    duration: 480, // 8小时
    maxStudents: 12,
    currentStudents: 9,
    level: 'beginner',
    tags: ['高尔夫基础', '挥杆技巧', '站姿', '握杆'],
    images: [
      'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800',
      'https://images.unsplash.com/photo-1593111774240-d529f12cf4b8?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.8,
    totalReviews: 65,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-3',
    title: '马术障碍赛进阶',
    description: '深入学习马术障碍赛技巧，包括跳跃技术、路线规划、时间控制等高级技能。适合有一定马术基础的学员。',
    coachId: 'coach-1',
    categoryId: 'cat-1',
    price: 650,
    duration: 720, // 12小时
    maxStudents: 6,
    currentStudents: 4,
    level: 'advanced',
    tags: ['障碍赛', '跳跃技术', '路线规划', '时间控制'],
    images: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.7,
    totalReviews: 42,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-4',
    title: '高尔夫短杆与推杆',
    description: '专注于高尔夫短杆技巧和推杆技术，包括切杆、沙坑球、推杆练习等。帮助你在果岭附近获得更好的成绩。',
    coachId: 'coach-2',
    categoryId: 'cat-2',
    price: 320,
    duration: 360, // 6小时
    maxStudents: 10,
    currentStudents: 7,
    level: 'intermediate',
    tags: ['短杆技巧', '推杆技术', '切杆', '沙坑球'],
    images: [
      'https://images.unsplash.com/photo-1593111774240-d529f12cf4b8?w=800',
      'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.6,
    totalReviews: 53,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];


