// 这是一个演示用的数据种子文件
// 在实际应用中，这些数据应该通过管理界面或API来创建

import { Timestamp } from 'firebase/firestore';

export const demoCategories = [
  {
    id: 'cat-1',
    name: '编程开发',
    description: '学习各种编程语言和开发技术',
    color: 'blue',
    icon: '💻',
    isActive: true,
    sortOrder: 1,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'cat-2',
    name: '设计创意',
    description: 'UI/UX设计、平面设计等创意技能',
    color: 'purple',
    icon: '🎨',
    isActive: true,
    sortOrder: 2,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'cat-3',
    name: '商业技能',
    description: '市场营销、项目管理等商业技能',
    color: 'green',
    icon: '💼',
    isActive: true,
    sortOrder: 3,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoUsers = [
  {
    id: 'user-1',
    email: 'john@example.com',
    displayName: 'John Smith',
    role: 'coach',
    bio: '拥有10年软件开发经验，专精于React和Node.js',
    location: '奥克兰',
    isVerified: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'user-2',
    email: 'sarah@example.com',
    displayName: 'Sarah Johnson',
    role: 'coach',
    bio: '资深UI/UX设计师，曾为多家知名公司设计产品',
    location: '惠灵顿',
    isVerified: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoCoaches = [
  {
    id: 'coach-1',
    userId: 'user-1',
    specialties: ['React', 'Node.js', 'TypeScript', 'JavaScript'],
    experience: 10,
    education: ['计算机科学学士', '软件工程硕士'],
    certifications: ['AWS认证开发者', 'Google Cloud认证'],
    hourlyRate: 120,
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: false,
      sunday: false,
    },
    rating: 4.8,
    totalReviews: 156,
    isActive: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'coach-2',
    userId: 'user-2',
    specialties: ['UI设计', 'UX设计', 'Figma', 'Adobe Creative Suite'],
    experience: 8,
    education: ['设计学士', '用户体验设计硕士'],
    certifications: ['Adobe认证专家', 'Google UX设计证书'],
    hourlyRate: 100,
    availability: {
      monday: true,
      tuesday: true,
      wednesday: true,
      thursday: true,
      friday: true,
      saturday: true,
      sunday: false,
    },
    rating: 4.9,
    totalReviews: 89,
    isActive: true,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];

export const demoCourses = [
  {
    id: 'course-1',
    title: 'React 从入门到精通',
    description: '学习现代React开发，包括Hooks、Context、状态管理等核心概念。通过实际项目练习，掌握React生态系统的最佳实践。',
    coachId: 'coach-1',
    categoryId: 'cat-1',
    price: 299,
    duration: 480, // 8小时
    maxStudents: 20,
    currentStudents: 15,
    level: 'intermediate',
    tags: ['React', 'JavaScript', '前端开发', 'Hooks'],
    images: [
      'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.8,
    totalReviews: 45,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-2',
    title: 'UI/UX设计基础',
    description: '从零开始学习UI/UX设计，包括设计原则、用户研究、原型制作等。适合设计新手和想要转行的开发者。',
    coachId: 'coach-2',
    categoryId: 'cat-2',
    price: 199,
    duration: 360, // 6小时
    maxStudents: 15,
    currentStudents: 12,
    level: 'beginner',
    tags: ['UI设计', 'UX设计', 'Figma', '用户研究'],
    images: [
      'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800',
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.9,
    totalReviews: 32,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-3',
    title: 'Node.js 后端开发',
    description: '深入学习Node.js后端开发，包括Express框架、数据库集成、API设计、部署等高级主题。',
    coachId: 'coach-1',
    categoryId: 'cat-1',
    price: 399,
    duration: 600, // 10小时
    maxStudents: 12,
    currentStudents: 8,
    level: 'advanced',
    tags: ['Node.js', 'Express', '后端开发', 'API设计'],
    images: [
      'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.7,
    totalReviews: 28,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    id: 'course-4',
    title: '数字营销策略',
    description: '学习现代数字营销策略，包括社交媒体营销、SEO、内容营销、数据分析等。适合创业者和小企业主。',
    coachId: 'coach-2',
    categoryId: 'cat-3',
    price: 149,
    duration: 240, // 4小时
    maxStudents: 25,
    currentStudents: 18,
    level: 'beginner',
    tags: ['数字营销', '社交媒体', 'SEO', '内容营销'],
    images: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    ],
    isActive: true,
    isPublished: true,
    rating: 4.6,
    totalReviews: 67,
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
];


